### ISSUE TITLE
Possible race condition in Theme loading

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-calendar-panel#142]
Feedback from the Grafana review team:

"- With the latest Grafana version (10.2.0) and the "Big calendar" calendar type, the style for the daily, weekly, and monthly views looks off. There are some thick white lines in the calendar. With the previous version of the plugin (v2.2.0), it looks correct.
- It also looks correct with the new version of the plugin (v2.3.0) and Grafana 10.1.0.

I could reproduce this issue only with plugin version v2.3.0 and Grafana 10.2.0."

Image: `grafana/grafana:10.2.0`

![Pasted image 20231103101938](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/47795110/49f1303f-ed0f-4ba9-8018-b8abfde2b62c)

**Comment by asimonok** [comment]
100% reproducable on grafana `10.1.5`. Steps:
- Open any page which doesn't contain the calendar panel (e.g. my profile)
- Open dashboard with the calendar panel
- The issue is appeared
- Refresh the page
- The issue is not appeared

Race condition was between imported styles by webpack and injected override styles by emotion. The Big calendar lib styles were cloned and inserted by emotion, this grants the right order.
