### ISSUE TITLE
Data->Color field setting all events to the same color regardless of selected field

### ISSUE THREAD

**Issue by alchemyyy** [VolkovLabs/volkovlabs-calendar-panel#189]
I'm still pretty new to Grafana and especially this plugin. So I'm not sure yet if I'm just missing something here.

I have event "types" that recur regularly. I would like to be able to give each type its own color. As these types change over time, using field overrides won't work. It is my understanding that this is what Data->Color (field to use as event color) is for. However, when setting the field to anything be it numerical ID, title, or description, all events are made to be the same color.

I have tried selecting both "classic palette" and "classic palette (by series name)" under standard options as well.

**Comment by carlocea9** [comment]
"Value mappings" field is what you are after. Just a few sections below the "Standard options (color scheme)"

**Comment by alchemyyy** [comment]
Ah yes what I meant instead of "field overrides" is "value mappings". I'm wondering if there's a way to achieve coloring without having to manually specify colors for values.

**Comment by mikhail-vl** [comment]
@alchemyyy Coloring explained in the documentation: https://volkovlabs.io/plugins/volkovlabs-calendar-panel/color/

  If you select a Color field, then it's evaluated based on the thresholds. Which is a native Grafana concept.

  Otherwise, select a Frame or Event in the coloring to display them using different colors.
