### ISSUE TITLE
User experience on drawer with large content is not very good

### ISSUE THREAD

**Issue by yusuf-multhan** [VolkovLabs/volkovlabs-calendar-panel#197]
What happened?
In continuation of this issue https://github.com/VolkovLabs/volkovlabs-calendar-panel/issues/157, When label content is a bit long, user experience is not very good, In older version labels with large content was taking the whole width of the drawer, making it readable. But with the new version, labels are restricted with fixed width and large content brings up the vertical scroll and make the experience bad.

Did this work before?
Yes - in old version - I believe it was v1.x

Attach dashboard snapshot below

Environment:
Grafana: 10.3.1

Old Snap v1.0.0
![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/9843492/c89a72e8-cf85-456c-b921-ab861d7a9c64)

New Snap V3.1.0
![image](https://github.com/VolkovLabs/volkovlabs-calendar-panel/assets/9843492/116120ab-bc22-49f5-ac64-d4b195e349c1)

Dashboard JSON
[New dashboard-1717585093298.json](https://github.com/user-attachments/files/15585826/New.dashboard-1717585093298.json)

**Comment by mikhail-vl** [comment]
@yusuf-multhan We update drawer layout #192 and it will be a part of the upcoming release.

  @vitPinchuk please test the provided dashboard that issue resolved.

**Comment by vitPinchuk** [comment]
@yusuf-multhan Thank you for your question 

Our current implementation and changes #157 #192 suggest using short text tags as labels. 
They can be 1-2 or more.

Previously they were not limited in width in pixels, and it was the reason why they broke a layout when the content was long. This was fixed in #157

We currently recommend using a description field for text with long content

The main changes drawer layout in #192 and it will be a part of the upcoming release

Thank you.

**Comment by mikhail-vl** [comment]
@yusuf-multhan Thank you for providing feedback.

@vitPinchuk We can consider to supporting multiple description fields like labels and display them one by one using the latest updates.
