### ISSUE TITLE
Invalid "N more..." label

### ISSUE THREAD

**Issue by yusuf-multhan** [VolkovLabs/volkovlabs-calendar-panel#68]
Hi,
I am facing this issue, where a day on calendar says "3 more..." where as actually that day only contains 2 events. Attaching SS here.
![image](https://user-images.githubusercontent.com/9843492/208405572-ef2a0ea5-652d-499d-ac73-f6f1fc5be3ce.png)

Also attaching sample dashboard JSON (convert .txt to .json).
[Calendar Issue for ...more rows-1671445911766.txt](https://github.com/VolkovLabs/volkovlabs-calendar-panel/files/10258465/Calendar.Issue.for.more.rows-1671445911766.txt)

Plugin version: v1.0.0, v1.1.0

**Comment by mikhail-vl** [comment]
@yusuf-multhan Thank you for your contribution.

  Please let us know if there is anything else.

**Comment by mikhail-vl** [comment]
You can download the artifact from the CI if you need it: https://github.com/VolkovLabs/volkovlabs-calendar-panel/actions/runs/3826757870

**Comment by mikhail-vl** [comment]
@yusuf-multhan I looked closer at this issue, and I understand the root cause why you see more events than displayed. It's a fillers for multi-day events. See on my screenshot.

![Screen Shot 2023-02-23 at 15 07 42](https://user-images.githubusercontent.com/47795110/221021501-4b8e3035-2e91-420c-bef3-c43655c716e6.png)

We can't just filter out `undefined` events, because multi-days lines will be broken.
I am looking how Google Calendar implemented it and they have similar concept of empty spaces. Except, that next week have to realign, but we align elements for the whole range.

It is something to improve in future versions, but for now I keep `undefined` events.
Let me know if it's clear. I am planning to release a new version later today and you are welcome to test it to see how it works for your use case.
